pipeline {
   agent none

    stages {
        stage('Build') {
        agent {
           docker {
              image 'python:2.7.16-slim'
              args  '--user root'
           }
        }

            steps {
                echo "Building vote app"
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('Test') {
        agent {
           docker {
              image 'python:2.7.16-slim'
              args  '--user root'
           }
        }

            steps {
              echo "Testing vote app"
              dir('vote'){
                  sh 'pip install -r requirements.txt'
                  sh 'nosetests -v'
              }
           }
        }

        stage('docker-Package') {
            agent any
            when {
              branch 'master'
            }
            steps {
                echo "Packaging vote app with docker"
                script{
                  docker.withRegistry('https://index.docker.io/v1/','dockerlogin'){
                  def voteImage = docker.build("anishpatel1281/vote:v${env.BUILD_ID}","./vote")
                  voteImage.push()
                  voteImage.push("${env.BRANCH_NAME}")
                  }

                }
            }
        }


    }
    post {
        always {
            echo "Build pipeline is completed for vote"
        }

    }
}
