pipeline {
    agent any
    tools {
     maven "maven 3.6.1"
    }
    stages {
        stage('Build') {
            when {
              changeset "**/worker/**"
                  }
            steps {
                echo "Building worker app"
                   dir('worker')
                    {
                    sh 'mvn compile'
                    }
            }
        }
        stage('Test') {
            when {
                  changeset "**/worker/**"
                  }          
            steps {
              echo "Testing worker app"
              dir('worker'){
              sh 'mvn clean test'
              }
            }
        }
        stage('Package') {
            when {
              branch 'master'
              changeset "**/worker/**"
            }
            steps {
                echo "Packaging worker app"
                dir('worker'){
                sh 'mvn package -DskipTests'
                }

            }
        }
    }
    post {
        always {
            echo "Build pipeline is completed"
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint:true
        }

    }
}
