pipeline {
   agent none

    stages {
        stage('Build') {
        agent {
           docker {
              image 'maven:3.6.1-jdk-8-alpine'
              args '-v $HOME/.m2:/root/.m2'
           }
        }

            steps {
                echo "Building worker app"
                   dir('worker')
                    {
                    sh 'mvn compile'
                    }
            }
        }
        stage('Test') {
        agent {
           docker {
              image 'maven:3.6.1-jdk-8-alpine'
              args '-v $HOME/.m2:/root/.m2'
           }
        }

            steps {
              echo "Testing worker app"
              dir('worker'){
              sh 'mvn clean test'
              }
            }
        }
        stage('Package') {
        agent {
           docker {
              image 'maven:3.6.1-jdk-8-alpine'
              args '-v $HOME/.m2:/root/.m2'
           }
        }
            when {
              branch 'master'
            }
            steps {
                echo "Packaging worker app"
                dir('worker'){
                sh 'mvn package -DskipTests'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint:true
                }

            }
        }

        stage('docker-Package') {
            agent any
            when {
              branch 'master'
            }
            steps {
                echo "Packaging worker app with docker"
                script{
                  docker.withRegistry('https://index.docker.io/v1','dockerlogin'){
                  def workerImage = docker.build("anishpatel1281/worker:v${env.BUILD_ID}","./worker")
                  workerImage.push()
                  workerImage.push("${env.BRANCH_NAME}")
                  }

                }
            }
        }

    }
    post {
        always {
            echo "Build pipeline for worker is completed now"
        }

    }
}
